### ISSUE TITLE
Systems No Longer Scraping

### ISSUE THREAD

**Issue by chewvodka** [meleu/hascheevos#13]
Not sure what's causing it.  Maybe the script can't download the hashes from RetroAchievements?  Did an update of the script tonight since I've not updated in over a month.  Script still runs, but doesn't find any games with cheevos in:

- Mega Drive / Genesis
- Master System
- GameBoy (original only, Color and Advance scrape fine)

Originally Reported Here:
https://retropie.org.uk/forum/topic/12563/retroachievements-in-a-nutshell/31
And in Discord PM :)

Seems like the script is also needlessly scanning my PSX roms, including all the music tracks (*.bin).  This will take HOURS to complete.  Original scrape time is already running me about 3-4 hours.  I've been scanning PSX for 2 hours now, and I'm only up to letter C.

**Comment by meleu** [comment]
hey @chewvodka 
I think all the issues you reported here were solved. Please, update your script and try again.

I'm closing this issue, but feel free to reopen if you are still having the same problems.

Thanks!
